name: fyn-rag-backend
region: nyc
services:
- name: backend
  github:
    repo: mcauduro0/fyn_rag
    branch: main
    deploy_on_push: true
  source_dir: /
  dockerfile_path: backend/Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-s
  envs:
  - key: OPENAI_API_KEY
    value: ${OPENAI_API_KEY}
  - key: ANTHROPIC_API_KEY
    value: ${ANTHROPIC_API_KEY}
  - key: POLYGON_API_KEY
    value: your_polygon_api_key_here
  - key: FMP_API_KEY
    value: your_fmp_api_key_here
  - key: TRADING_ECONOMICS_API_KEY
    value: DB5A57F91781451:A8A888DFE5F9495
  - key: FRED_API_KEY
    value: e63bf4ad4b21136be0b68c27e7e510d9
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: ENVIRONMENT
    value: staging
databases:
- name: db
  engine: PG
  version: "15"
  production: false
  cluster_name: fyn-rag-db
  num_nodes: 1

