"""
Report Generator - Creates institutional-grade investment reports.
Supports One-Pager Memos, Comprehensive Thesis, and Presentations.
"""

import logging
from typing import Dict, Any, List, Optional
from datetime import datetime
from enum import Enum

logger = logging.getLogger(__name__)


class ReportType(str, Enum):
    """Types of investment reports."""
    ONE_PAGER = "one_pager"
    COMPREHENSIVE_THESIS = "comprehensive_thesis"
    PRESENTATION = "presentation"
    EXECUTIVE_SUMMARY = "executive_summary"


class ReportSection:
    """Represents a section of a report."""
    
    def __init__(
        self,
        title: str,
        content: str,
        subsections: Optional[List['ReportSection']] = None
    ):
        self.title = title
        self.content = content
        self.subsections = subsections or []
    
    def to_markdown(self, level: int = 2) -> str:
        """Convert section to Markdown."""
        md_parts = []
        
        # Section title
        md_parts.append(f"{'#' * level} {self.title}\n")
        
        # Content
        if self.content:
            md_parts.append(f"{self.content}\n")
        
        # Subsections
        for subsection in self.subsections:
            md_parts.append(subsection.to_markdown(level + 1))
        
        return "\n".join(md_parts)


class InvestmentReport:
    """Base class for investment reports."""
    
    def __init__(
        self,
        report_type: ReportType,
        company_name: str,
        ticker: Optional[str] = None,
        analyst: str = "Fyn RAG Investment Committee"
    ):
        self.report_type = report_type
        self.company_name = company_name
        self.ticker = ticker
        self.analyst = analyst
        self.date = datetime.utcnow()
        self.sections: List[ReportSection] = []
        self.metadata: Dict[str, Any] = {}
    
    def add_section(self, section: ReportSection) -> None:
        """Add a section to the report."""
        self.sections.append(section)
    
    def to_markdown(self) -> str:
        """Convert report to Markdown format."""
        md_parts = []
        
        # Header
        md_parts.append(self._generate_header())
        
        # Sections
        for section in self.sections:
            md_parts.append(section.to_markdown())
        
        # Footer
        md_parts.append(self._generate_footer())
        
        return "\n\n".join(md_parts)
    
    def _generate_header(self) -> str:
        """Generate report header."""
        header_parts = [
            f"# Investment Analysis: {self.company_name}",
            f"**Ticker:** {self.ticker or 'N/A'}",
            f"**Date:** {self.date.strftime('%B %d, %Y')}",
            f"**Analyst:** {self.analyst}",
            f"**Report Type:** {self.report_type.value.replace('_', ' ').title()}",
            "\n---\n"
        ]
        return "\n".join(header_parts)
    
    def _generate_footer(self) -> str:
        """Generate report footer."""
        footer = [
            "\n---\n",
            "*This report was generated by the Fyn RAG Investment Committee System.*",
            "*All analysis is based on available data and investment frameworks.*",
            f"*Generated: {self.date.isoformat()}*"
        ]
        return "\n".join(footer)


class ReportGenerator:
    """
    Report Generator creates institutional-grade investment reports.
    
    Supported report types:
    1. One-Pager Investment Memo
    2. Comprehensive Investment Thesis
    3. Investment Committee Presentation
    4. Executive Summary
    """
    
    def __init__(self):
        logger.info("Initialized Report Generator")
    
    def generate_one_pager(
        self,
        company_name: str,
        ticker: Optional[str],
        analysis_data: Dict[str, Any],
        recommendation: str,
        confidence: float
    ) -> InvestmentReport:
        """
        Generate a one-page investment memo.
        
        Args:
            company_name: Company name
            ticker: Stock ticker
            analysis_data: Complete analysis data from agents
            recommendation: Final recommendation
            confidence: Confidence score
            
        Returns:
            InvestmentReport with one-pager format
        """
        logger.info(f"Generating one-pager for {company_name}")
        
        report = InvestmentReport(
            report_type=ReportType.ONE_PAGER,
            company_name=company_name,
            ticker=ticker
        )
        
        # Executive Summary
        exec_summary = self._create_executive_summary(
            recommendation,
            confidence,
            analysis_data
        )
        report.add_section(exec_summary)
        
        # Investment Highlights
        highlights = self._create_investment_highlights(analysis_data)
        report.add_section(highlights)
        
        # Key Risks
        risks = self._create_key_risks(analysis_data)
        report.add_section(risks)
        
        # Valuation Summary
        valuation = self._create_valuation_summary(analysis_data)
        report.add_section(valuation)
        
        # Recommendation
        rec_section = self._create_recommendation_section(
            recommendation,
            confidence
        )
        report.add_section(rec_section)
        
        return report
    
    def generate_comprehensive_thesis(
        self,
        company_name: str,
        ticker: Optional[str],
        analysis_data: Dict[str, Any],
        recommendation: str,
        confidence: float
    ) -> InvestmentReport:
        """
        Generate a comprehensive investment thesis.
        
        Args:
            company_name: Company name
            ticker: Stock ticker
            analysis_data: Complete analysis data from agents
            recommendation: Final recommendation
            confidence: Confidence score
            
        Returns:
            InvestmentReport with comprehensive format
        """
        logger.info(f"Generating comprehensive thesis for {company_name}")
        
        report = InvestmentReport(
            report_type=ReportType.COMPREHENSIVE_THESIS,
            company_name=company_name,
            ticker=ticker
        )
        
        # All sections from one-pager
        report.add_section(self._create_executive_summary(recommendation, confidence, analysis_data))
        report.add_section(self._create_investment_highlights(analysis_data))
        
        # Additional detailed sections
        report.add_section(self._create_business_overview(analysis_data))
        report.add_section(self._create_industry_analysis(analysis_data))
        report.add_section(self._create_competitive_position(analysis_data))
        report.add_section(self._create_financial_analysis(analysis_data))
        report.add_section(self._create_valuation_analysis(analysis_data))
        report.add_section(self._create_risk_analysis(analysis_data))
        report.add_section(self._create_growth_analysis(analysis_data))
        report.add_section(self._create_forensics_analysis(analysis_data))
        report.add_section(self._create_recommendation_section(recommendation, confidence))
        
        return report
    
    def generate_presentation_outline(
        self,
        company_name: str,
        ticker: Optional[str],
        analysis_data: Dict[str, Any],
        recommendation: str,
        confidence: float
    ) -> InvestmentReport:
        """
        Generate an investment committee presentation outline.
        
        Args:
            company_name: Company name
            ticker: Stock ticker
            analysis_data: Complete analysis data from agents
            recommendation: Final recommendation
            confidence: Confidence score
            
        Returns:
            InvestmentReport with presentation format
        """
        logger.info(f"Generating presentation outline for {company_name}")
        
        report = InvestmentReport(
            report_type=ReportType.PRESENTATION,
            company_name=company_name,
            ticker=ticker
        )
        
        # Slide-by-slide outline
        slides = [
            ("Title Slide", f"{company_name} Investment Analysis"),
            ("Executive Summary", self._create_exec_summary_bullet_points(recommendation, confidence, analysis_data)),
            ("Investment Thesis", self._create_thesis_bullet_points(analysis_data)),
            ("Market Opportunity", self._create_market_bullet_points(analysis_data)),
            ("Competitive Position", self._create_competitive_bullet_points(analysis_data)),
            ("Financial Performance", self._create_financial_bullet_points(analysis_data)),
            ("Valuation", self._create_valuation_bullet_points(analysis_data)),
            ("Risk Factors", self._create_risk_bullet_points(analysis_data)),
            ("Recommendation", self._create_recommendation_bullet_points(recommendation, confidence))
        ]
        
        for i, (title, content) in enumerate(slides, 1):
            section = ReportSection(
                title=f"Slide {i}: {title}",
                content=content
            )
            report.add_section(section)
        
        return report
    
    def _create_executive_summary(
        self,
        recommendation: str,
        confidence: float,
        analysis_data: Dict[str, Any]
    ) -> ReportSection:
        """Create executive summary section."""
        
        # Extract key points from analysis
        key_points = []
        
        if "value_analysis" in analysis_data:
            margin = analysis_data["value_analysis"].get("margin_of_safety")
            if margin:
                key_points.append(f"Trading at {abs(margin):.0%} {'discount' if margin > 0 else 'premium'} to intrinsic value")
        
        if "growth_analysis" in analysis_data:
            growth = analysis_data["growth_analysis"].get("growth_rate")
            if growth:
                key_points.append(f"Revenue growing at {growth:.0%} annually")
        
        content = f"""
**Recommendation:** {recommendation}  
**Confidence Level:** {confidence:.0%}

{chr(10).join('- ' + point for point in key_points[:3])}

This analysis synthesizes insights from our multi-agent investment committee, 
incorporating value investing, growth analysis, risk management, industry dynamics, 
and financial forensics perspectives.
"""
        
        return ReportSection("Executive Summary", content.strip())
    
    def _create_investment_highlights(self, analysis_data: Dict[str, Any]) -> ReportSection:
        """Create investment highlights section."""
        
        highlights = []
        
        # Collect opportunities from all agents
        for agent_key in ["value_analysis", "growth_analysis", "industry_analysis"]:
            if agent_key in analysis_data:
                agent_data = analysis_data[agent_key]
                if "opportunities" in agent_data:
                    highlights.extend(agent_data["opportunities"][:2])
        
        content = "\n".join(f"- {h}" for h in highlights[:5])
        
        return ReportSection("Investment Highlights", content)
    
    def _create_key_risks(self, analysis_data: Dict[str, Any]) -> ReportSection:
        """Create key risks section."""
        
        risks = []
        
        # Collect concerns from all agents
        for agent_key in ["risk_analysis", "forensics_analysis", "industry_analysis"]:
            if agent_key in analysis_data:
                agent_data = analysis_data[agent_key]
                if "concerns" in agent_data:
                    risks.extend(agent_data["concerns"][:2])
        
        content = "\n".join(f"- {r}" for r in risks[:5])
        
        return ReportSection("Key Risks", content)
    
    def _create_valuation_summary(self, analysis_data: Dict[str, Any]) -> ReportSection:
        """Create valuation summary section."""
        
        content_parts = []
        
        if "value_analysis" in analysis_data:
            val = analysis_data["value_analysis"]
            if "intrinsic_value" in val:
                content_parts.append(f"**Intrinsic Value:** ${val['intrinsic_value']:.2f}")
            if "margin_of_safety" in val:
                content_parts.append(f"**Margin of Safety:** {val['margin_of_safety']:.1%}")
        
        content = "\n".join(content_parts) if content_parts else "Valuation data not available"
        
        return ReportSection("Valuation Summary", content)
    
    def _create_recommendation_section(
        self,
        recommendation: str,
        confidence: float
    ) -> ReportSection:
        """Create recommendation section."""
        
        content = f"""
**Final Recommendation:** {recommendation}  
**Confidence Level:** {confidence:.0%}

This recommendation represents the consensus view of our investment committee 
after thorough analysis and debate among specialized agents.
"""
        
        return ReportSection("Recommendation", content.strip())
    
    def _create_business_overview(self, analysis_data: Dict[str, Any]) -> ReportSection:
        """Create business overview section."""
        content = "Comprehensive business description and operations overview."
        return ReportSection("Business Overview", content)
    
    def _create_industry_analysis(self, analysis_data: Dict[str, Any]) -> ReportSection:
        """Create industry analysis section."""
        
        content_parts = []
        
        if "industry_analysis" in analysis_data:
            ind = analysis_data["industry_analysis"]
            if "porters_five_forces" in ind:
                content_parts.append(f"**Industry Attractiveness:** {ind['porters_five_forces'].get('overall_attractiveness', 'N/A').upper()}")
            if "industry_lifecycle" in ind:
                content_parts.append(f"**Lifecycle Stage:** {ind['industry_lifecycle'].get('stage', 'N/A').upper()}")
        
        content = "\n\n".join(content_parts) if content_parts else "Industry analysis data not available"
        
        return ReportSection("Industry Analysis", content)
    
    def _create_competitive_position(self, analysis_data: Dict[str, Any]) -> ReportSection:
        """Create competitive position section."""
        content = "Analysis of competitive positioning and market share."
        return ReportSection("Competitive Position", content)
    
    def _create_financial_analysis(self, analysis_data: Dict[str, Any]) -> ReportSection:
        """Create financial analysis section."""
        content = "Detailed financial statement analysis and trends."
        return ReportSection("Financial Analysis", content)
    
    def _create_valuation_analysis(self, analysis_data: Dict[str, Any]) -> ReportSection:
        """Create valuation analysis section."""
        content = "Comprehensive valuation using multiple methodologies."
        return ReportSection("Valuation Analysis", content)
    
    def _create_risk_analysis(self, analysis_data: Dict[str, Any]) -> ReportSection:
        """Create risk analysis section."""
        content = "Detailed risk assessment and mitigation strategies."
        return ReportSection("Risk Analysis", content)
    
    def _create_growth_analysis(self, analysis_data: Dict[str, Any]) -> ReportSection:
        """Create growth analysis section."""
        content = "Growth trajectory and expansion opportunities."
        return ReportSection("Growth Analysis", content)
    
    def _create_forensics_analysis(self, analysis_data: Dict[str, Any]) -> ReportSection:
        """Create forensics analysis section."""
        content = "Financial statement quality and red flag assessment."
        return ReportSection("Financial Forensics", content)
    
    def _create_exec_summary_bullet_points(
        self,
        recommendation: str,
        confidence: float,
        analysis_data: Dict[str, Any]
    ) -> str:
        """Create executive summary bullet points for presentation."""
        return f"""
- **Recommendation:** {recommendation}
- **Confidence:** {confidence:.0%}
- Multi-agent analysis consensus
- Comprehensive risk assessment completed
"""
    
    def _create_thesis_bullet_points(self, analysis_data: Dict[str, Any]) -> str:
        """Create investment thesis bullet points."""
        return "- Key thesis point 1\n- Key thesis point 2\n- Key thesis point 3"
    
    def _create_market_bullet_points(self, analysis_data: Dict[str, Any]) -> str:
        """Create market opportunity bullet points."""
        return "- Market size and growth\n- Addressable opportunity\n- Competitive landscape"
    
    def _create_competitive_bullet_points(self, analysis_data: Dict[str, Any]) -> str:
        """Create competitive position bullet points."""
        return "- Market position\n- Competitive advantages\n- Barriers to entry"
    
    def _create_financial_bullet_points(self, analysis_data: Dict[str, Any]) -> str:
        """Create financial performance bullet points."""
        return "- Revenue trends\n- Profitability metrics\n- Cash flow generation"
    
    def _create_valuation_bullet_points(self, analysis_data: Dict[str, Any]) -> str:
        """Create valuation bullet points."""
        return "- Intrinsic value estimate\n- Valuation multiples\n- Margin of safety"
    
    def _create_risk_bullet_points(self, analysis_data: Dict[str, Any]) -> str:
        """Create risk factors bullet points."""
        return "- Key risk factor 1\n- Key risk factor 2\n- Mitigation strategies"
    
    def _create_recommendation_bullet_points(
        self,
        recommendation: str,
        confidence: float
    ) -> str:
        """Create recommendation bullet points."""
        return f"""
- **Action:** {recommendation}
- **Confidence:** {confidence:.0%}
- **Next Steps:** Monitor key metrics
- **Review Date:** Quarterly
"""


if __name__ == "__main__":
    # Test report generation
    generator = ReportGenerator()
    
    # Mock analysis data
    analysis_data = {
        "value_analysis": {
            "intrinsic_value": 150.00,
            "margin_of_safety": 0.25,
            "opportunities": ["Undervalued relative to peers"],
            "concerns": []
        },
        "growth_analysis": {
            "growth_rate": 0.30,
            "opportunities": ["Large addressable market"],
            "concerns": []
        },
        "risk_analysis": {
            "concerns": ["High volatility"]
        }
    }
    
    # Generate one-pager
    report = generator.generate_one_pager(
        company_name="Apple Inc.",
        ticker="AAPL",
        analysis_data=analysis_data,
        recommendation="BUY",
        confidence=0.8
    )
    
    print(report.to_markdown())
